# Generated by Django 5.0.2 on 2024-02-14 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_App.ciudad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField(default=False)),
                ('hoteles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel_App.hoteles')),
            ],
        ),
    ]
