# Generated by Django 5.0.1 on 2024-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
